name: Yogiji
favicon: null
layout_spectrum: 0.73354
typography_spectrum: 0.51337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3ded2'
    - '#110a06'
    - '#573632'
    - '#b5a78c'
    - '#80574c'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
