name: Yogiji
favicon: null
layout_spectrum: 0.73354
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3ded2'
    - '#110a06'
    - '#573632'
    - '#b5a78c'
    - '#80574c'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
